import { defineMiddleware } from "astro:middleware";

/**
 * Cache-Control header for long-lived static assets.
 *
 * Astro content-hashes built JS/CSS bundles under `/_astro/`, so they are
 * safe to cache immutably for a year. Files in `public/` (fonts, logos,
 * favicon, robots.txt) are not hashed but change rarely and are also safe
 * for aggressive caching. A new deploy purges the Render edge cache anyway.
 */
const IMMUTABLE_CACHE = "public, max-age=31536000, immutable";

/**
 * Paths that should receive immutable long-lived cache headers.
 *
 * - `/_astro/` — hashed JS/CSS bundles generated by the Astro/Vite build
 * - `/fonts/` — self-hosted woff2 font files
 * - `/agency-logos/` — transit agency SVG logos
 * - `/favicon.svg`, `/robots.txt` — static root-level files
 */
const IMMUTABLE_PREFIXES = ["/_astro/", "/fonts/", "/agency-logos/"];
const IMMUTABLE_EXACT = new Set(["/favicon.svg", "/robots.txt"]);

/**
 * Middleware that sets aggressive `Cache-Control: immutable` headers on
 * static assets so Render's edge CDN caches them for a year. Without this,
 * Render applies its default 120-minute TTL to responses that lack an
 * explicit `Cache-Control` header, which is suboptimal for cacheable assets.
 *
 * API routes and HTML pages are left untouched — they set their own headers
 * (via `prodCacheHeader`) or receive Render's default behavior.
 */
export const onRequest = defineMiddleware(async (context, next) => {
  const pathname = context.url.pathname;

  const isImmutable =
    IMMUTABLE_PREFIXES.some((p) => pathname.startsWith(p)) ||
    IMMUTABLE_EXACT.has(pathname);

  if (!isImmutable) {
    return next();
  }

  const res = await next();

  // Only set the header if the response doesn't already have one
  // (don't override headers explicitly set by endpoints).
  if (!res.headers.has("Cache-Control")) {
    res.headers.set("Cache-Control", IMMUTABLE_CACHE);
  }

  return res;
});
